# Project information
site_name: Schuldatentransferformat
site_description: 'Dokumentation zum Schuldatentransferformat'
site_author: 'STÜBER SYSTEMS GmbH'
site_url: 'https://doc.sdtf.stueber.de'

# Copyright
copyright: © 2020 STÜBER SYSTEMS GmbH

# Repository
repo_name: 'Auf GitHub'
repo_url: 'https://github.com/stuebersystems/doc.sdtf.de'

# Theming
theme: 
    name: material
    custom_dir: overrides
    language: de
    feature:
        - tabs
        - instant
    palette:
        primary: 'indigo'
        accent: 'amber'
    font: false
    favicon: assets/logos/favicon.ico
    logo: 'assets/logos/logo.svg'
    include_search_page: false
    search_index_only: true
    static_templates:
      - 404.html

# Legal links
extra:
  legal:
    - label: Impressum
      link: https://www.stueber.de/imprint.php
    - label: Datenschutz
      link: https://legal.stueber.de/

# Customization
extra_css:
    - assets/css/custom.css

# Extensions    
markdown_extensions:
    - admonition
  
# Navigation  
nav:
- Überblick: index.md
- Zeilenaufbau: zeilenaufbau.md
- Unterrichtsart und Fachstatus: unterrichtsart-und-fachstatus.md
- DAVINCI-Zeilentypen: davinci-zeilentypen.md
- MAGELLAN-Zeilentypen: magellan-zeilentypen.md
- DAVINCI-Anonymisierung: davinci-anonymisierung.md
